using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace GLEngine.Config
{
    public class ConfigFileConstant
    {
        public static readonly string F_Editor_Window_Conf = "EditorWindowConf";
    }

    public class ConfigKey
    {
        public static readonly string Category_Advanced = "Category_Advanced";
        public static readonly string Category_Diagnostics = "Category_Diagnostics";
        public static readonly string Category_General = "Category_General";
        public static readonly string Category_Graphics = "Category_Graphics";
        public static readonly string Category_Physics = "Category_Physics";
        public static readonly string Category_Sound = "Category_Sound";
        public static readonly string EditorApplicationTitle = "EditorApplicationTitle";
        public static readonly string HelpInfo_NotAvailable_Desc = "HelpInfo_NotAvailable_Desc";
        public static readonly string Language = "Language";
        public static readonly string LicenseAcceptDialog_FirstStartGeneric = "LicenseAcceptDialog_FirstStartGeneric";
        public static readonly string LicenseAcceptDialog_PackageDesc = "LicenseAcceptDialog_PackageDesc";
        public static readonly string LicenseAcceptDialog_TranscriptUnavailable = "LicenseAcceptDialog_TranscriptUnavailable";
        public static readonly string MenuItemInfo_ConfigureLauncher = "MenuItemInfo_ConfigureLauncher";
        public static readonly string MenuItemInfo_OpenProjectSource = "MenuItemInfo_OpenProjectSource";
        public static readonly string MenuItemInfo_ProfileGame = "MenuItemInfo_ProfileGame";
        public static readonly string MenuItemInfo_PublishGame = "MenuItemInfo_PublishGame";
        public static readonly string MenuItemInfo_RunGame = "MenuItemInfo_RunGame";
        public static readonly string MenuItemInfo_SaveAll = "MenuItemInfo_SaveAll";
        public static readonly string MenuItemInfo_SerializerUpdateAll = "MenuItemInfo_SerializerUpdateAll";
        public static readonly string MenuItemInfo_ToggleBackups = "MenuItemInfo_ToggleBackups";
        public static readonly string MenuItemName_About = "MenuItemName_About";
        public static readonly string MenuItemName_ConfigureLauncher = "MenuItemName_ConfigureLauncher";
        public static readonly string MenuItemName_ProfileGame = "MenuItemName_ProfileGame";
        public static readonly string MenuItemName_PublishGame = "MenuItemName_PublishGame";
        public static readonly string MenuItemName_Quit = "MenuItemName_Quit";
        public static readonly string MenuItemName_Redo = "MenuItemName_Redo";
        public static readonly string MenuItemName_RedoEmpty = "MenuItemName_RedoEmpty";
        public static readonly string MenuItemName_SerializerUpdateAll = "MenuItemName_SerializerUpdateAll";
        public static readonly string MenuItemName_Undo = "MenuItemName_Undo";
        public static readonly string MenuItemName_UndoEmpty = "MenuItemName_UndoEmpty";
        public static readonly string MenuItemName_WelcomeDialog = "MenuItemName_WelcomeDialog";
        public static readonly string MenuName_Edit = "MenuName_Edit";
        public static readonly string MenuName_File = "MenuName_File";
        public static readonly string MenuName_Help = "MenuName_Help";
        public static readonly string MenuName_Run = "MenuName_Run";
        public static readonly string MenuName_Settings = "MenuName_Settings";
        public static readonly string MenuName_Tools = "MenuName_Tools";
        public static readonly string MenuName_View = "MenuName_View";
        public static readonly string Msg_CantExport_Caption = "Msg_CantExport_Caption";
        public static readonly string Msg_CantExport_Text = "Msg_CantExport_Text";
        public static readonly string Msg_CantImport_Caption = "Msg_CantImport_Caption";
        public static readonly string Msg_CantImport_Text = "Msg_CantImport_Text";
        public static readonly string Msg_ConfirmBreakPrefabLink_Caption = "Msg_ConfirmBreakPrefabLink_Caption";
        public static readonly string Msg_ConfirmBreakPrefabLink_Desc = "Msg_ConfirmBreakPrefabLink_Desc";
        public static readonly string Msg_ConfirmDeleteSelectedObjects_Caption = "Msg_ConfirmDeleteSelectedObjects_Caption";
        public static readonly string Msg_ConfirmDeleteSelectedObjects_Text = "Msg_ConfirmDeleteSelectedObjects_Text";
        public static readonly string Msg_ConfirmQuit_Caption = "Msg_ConfirmQuit_Caption";
        public static readonly string Msg_ConfirmQuit_Desc = "Msg_ConfirmQuit_Desc";
        public static readonly string Msg_ConfirmQuitUnsaved_Caption = "Msg_ConfirmQuitUnsaved_Caption";
        public static readonly string Msg_ConfirmQuitUnsaved_Desc = "Msg_ConfirmQuitUnsaved_Desc";
        public static readonly string Msg_ConfirmQuitUnsaved_Desc_More = "Msg_ConfirmQuitUnsaved_Desc_More";
        public static readonly string Msg_ConfirmReloadResource_Caption = "Msg_ConfirmReloadResource_Caption";
        public static readonly string Msg_ConfirmReloadResource_Text = "Msg_ConfirmReloadResource_Text";
        public static readonly string Msg_CreateProjectErrorNestedFolder_Caption = "Msg_CreateProjectErrorNestedFolder_Caption";
        public static readonly string Msg_CreateProjectErrorNestedFolder_Desc = "Msg_CreateProjectErrorNestedFolder_Desc";
        public static readonly string Msg_CreateProjectErrorTargetExists_Caption = "Msg_CreateProjectErrorTargetExists_Caption";
        public static readonly string Msg_CreateProjectErrorTargetExists_Desc = "Msg_CreateProjectErrorTargetExists_Desc";
        public static readonly string Msg_CreateProjectErrorTargetIsFilePath_Desc = "Msg_CreateProjectErrorTargetIsFilePath_Desc";
        public static readonly string Msg_ErrorPerformBigTask_Caption = "Msg_ErrorPerformBigTask_Caption";
        public static readonly string Msg_ErrorPerformBigTask_Desc = "Msg_ErrorPerformBigTask_Desc";
        public static readonly string Msg_ErrorReloadCorePlugin_Caption = "Msg_ErrorReloadCorePlugin_Caption";
        public static readonly string Msg_ErrorReloadCorePlugin_Desc = "Msg_ErrorReloadCorePlugin_Desc";
        public static readonly string Msg_ImportConfirmOverwrite_Caption = "Msg_ImportConfirmOverwrite_Caption";
        public static readonly string Msg_ImportConfirmOverwrite_Text = "Msg_ImportConfirmOverwrite_Text";
        public static readonly string Msg_InstallNewTemplate_Caption = "Msg_InstallNewTemplate_Caption";
        public static readonly string Msg_InstallNewTemplate_Desc = "Msg_InstallNewTemplate_Desc";
        public static readonly string MsgLicenseNotAgreedAbort_Caption = "MsgLicenseNotAgreedAbort_Caption";
        public static readonly string MsgLicenseNotAgreedAbort_Desc = "MsgLicenseNotAgreedAbort_Desc";
        public static readonly string OpenTemplateDialog_Filters = "OpenTemplateDialog_Filters";
        public static readonly string OpenTemplateDialog_Title = "OpenTemplateDialog_Title";
        public static readonly string PropertyGrid_N_Objects = "PropertyGrid_N_Objects";
        public static readonly string TaskBarOverlay_ReloadCorePlugin_Desc = "TaskBarOverlay_ReloadCorePlugin_Desc";
        public static readonly string TaskChangeDataFormat_Caption = "TaskChangeDataFormat_Caption";
        public static readonly string TaskChangeDataFormat_Desc = "TaskChangeDataFormat_Desc";
        public static readonly string TaskFormatUpdateAll_Caption = "TaskFormatUpdateAll_Caption";
        public static readonly string TaskFormatUpdateAll_Desc = "TaskFormatUpdateAll_Desc";
        public static readonly string TaskInstallPackages_Caption = "TaskInstallPackages_Caption";
        public static readonly string TaskInstallPackages_Desc = "TaskInstallPackages_Desc";
        public static readonly string TaskPrepareInfo = "TaskPrepareInfo";
        public static readonly string TaskRenameContentRefs_Caption = "TaskRenameContentRefs_Caption";
        public static readonly string TaskRenameContentRefs_Desc = "TaskRenameContentRefs_Desc";
        public static readonly string Template_Current_Desc = "Template_Current_Desc";
        public static readonly string Template_Current_Name = "Template_Current_Name";
        public static readonly string Template_Empty_Desc = "Template_Empty_Desc";
        public static readonly string Template_Empty_Name = "Template_Empty_Name";
        public static readonly string UndoRedo_AddToDictionary = "UndoRedo_AddToDictionary";
        public static readonly string UndoRedo_ApplyToPrefab = "UndoRedo_ApplyToPrefab";
        public static readonly string UndoRedo_ApplyToPrefabMulti = "UndoRedo_ApplyToPrefabMulti";
        public static readonly string UndoRedo_BreakPrefabLink = "UndoRedo_BreakPrefabLink";
        public static readonly string UndoRedo_BreakPrefabLinkMulti = "UndoRedo_BreakPrefabLinkMulti";
        public static readonly string UndoRedo_CloneGameObject = "UndoRedo_CloneGameObject";
        public static readonly string UndoRedo_CloneGameObjectMulti = "UndoRedo_CloneGameObjectMulti";
        public static readonly string UndoRedo_CreateComponent = "UndoRedo_CreateComponent";
        public static readonly string UndoRedo_CreateComponentMulti = "UndoRedo_CreateComponentMulti";
        public static readonly string UndoRedo_CreateGameObject = "UndoRedo_CreateGameObject";
        public static readonly string UndoRedo_CreateGameObjectMulti = "UndoRedo_CreateGameObjectMulti";
        public static readonly string UndoRedo_DeleteComponent = "UndoRedo_DeleteComponent";
        public static readonly string UndoRedo_DeleteComponentMulti = "UndoRedo_DeleteComponentMulti";
        public static readonly string UndoRedo_DeleteGameObject = "UndoRedo_DeleteGameObject";
        public static readonly string UndoRedo_DeleteGameObjectMulti = "UndoRedo_DeleteGameObjectMulti";
        public static readonly string UndoRedo_EditProperty = "UndoRedo_EditProperty";
        public static readonly string UndoRedo_Macro = "UndoRedo_Macro";
        public static readonly string UndoRedo_PasteGameObject = "UndoRedo_PasteGameObject";
        public static readonly string UndoRedo_PasteGameObjectMulti = "UndoRedo_PasteGameObjectMulti";
        public static readonly string UndoRedo_RemoveFromDictionary = "UndoRedo_RemoveFromDictionary";
        public static readonly string UndoRedo_ResetComponent = "UndoRedo_ResetComponent";
        public static readonly string UndoRedo_ResetComponentMulti = "UndoRedo_ResetComponentMulti";
        public static readonly string UndoRedo_ResetGameObject = "UndoRedo_ResetGameObject";
        public static readonly string UndoRedo_ResetGameObjectMulti = "UndoRedo_ResetGameObjectMulti";
        public static readonly string UndoRedo_ResizeILists = "UndoRedo_ResizeILists";
        public static readonly string UndoRedo_SetComponentParent = "UndoRedo_SetComponentParent";
        public static readonly string UndoRedo_SetComponentParentMulti = "UndoRedo_SetComponentParentMulti";
        public static readonly string UndoRedo_SetGameObjectName = "UndoRedo_SetGameObjectName";
        public static readonly string UndoRedo_SetGameObjectNameMulti = "UndoRedo_SetGameObjectNameMulti";
        public static readonly string UndoRedo_SetGameObjectParent = "UndoRedo_SetGameObjectParent";
        public static readonly string UndoRedo_SetGameObjectParentMulti = "UndoRedo_SetGameObjectParentMulti";
    }
}
